name: Android Setup
description: Common Android CI setup (JDK, Gradle, Firebase config)

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
        cache: gradle

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Decode google-services.json
      shell: bash
      run: |
        echo "$GOOGLE_SERVICES_JSON" | base64 --decode > app/google-services.json
      env:
        GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}