name: Android Setup
description: Common Android CI setup (JDK, Gradle, Firebase config)

inputs:
  google-services-json:
    description: "Base64 encoded google-services.json"
    required: true

runs:
  using: composite
  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
        cache: gradle

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Decode google-services.json
      shell: bash
      run: |
        echo "${{ inputs.google-services-json }}" | base64 --decode > app/google-services.json